# -*- coding: utf-8 -*-
"""Catalogo de bancos del SPI.

Lo publica el Banco Central y lo usa el archivo de pagos de Produbanco:
el TXT lleva el codigo, no el nombre. Vivia solo en la hoja "COD BANCOS"
del Excel que alguien guardaba en Downloads; aqui esta versionado con el
resto del codigo, que es donde se puede revisar que cambio y cuando.

No es una tabla a proposito: no se edita desde la aplicacion, cambia una
vez al ano y no vale una migracion.

Formato: (codigo, nombre, activo_para_pagos)
"""

BANCOS = [
    ('34',   'AMAZONAS',                                True ),
    ('35',   'AUSTRO',                                  True ),
    ('61',   'BANCO CAPITAL',                           True ),
    ('1',    'BANCO CENTRAL',                           True ),
    ('64',   'BANCO COOPNACIONAL SA',                   True ),
    ('183',  'BANCO D MIRO SA',                         True ),
    ('539',  'BANCO DEL INSTITUTO ECUATORIANO DE SEGURIDAD SOCIA', True ),
    ('65',   'BANCO DESARROLLO DE LOS PUEBLOS S.A.',    True ),
    ('62',   'BANCO PARA LA ASISTENCIA COMUNITARIA FINCA S.A.', True ),
    ('60',   'BANCO PROCREDIT',                         True ),
    ('66',   'BANECUADOR B.P.',                         True ),
    ('37',   'BOLIVARIANO',                             True ),
    ('589',  'CASA DE VALORES SMARTCAPITAL S. A. MV',   True ),
    ('24',   'CITIBANK',                                True ),
    ('39',   'COMERCIAL DE MANABI',                     True ),
    ('408',  'COOP A Y C CADECOG GONZANAMA',            True ),
    ('432',  'COOP A Y C ESPERANZA Y PROGRESO DEL VALLE', True ),
    ('406',  'COOP A Y C UNION EL EJIDO',               True ),
    ('407',  'COOP A Y C VILCABAMBA CACVIL',            True ),
    ('368',  'COOP AH Y CR ANDINA LTDA',                True ),
    ('592',  'COOP AH Y CR CHUNCHI LTDA',               True ),
    ('257',  'COOP AH Y CR COCA LTDA',                  True ),
    ('270',  'COOP AH Y CR CREDIAMIGO',                 True ),
    ('590',  'COOP AH Y CR DE INDIGENAS CHUCHUQUI LTDA', True ),
    ('230',  'COOP AH Y CR EDUCADORES DE PASTAZA LTDA', True ),
    ('168',  'COOP AH Y CR POLICIA NACIONAL',           True ),
    ('222',  'COOP AH Y CR SAN ANTONIO LTDA.',          True ),
    ('229',  'COOP AH Y CRJUAN PIO MORA LTDA',          True ),
    ('214',  'COOP AHO Y CRED EDUCADORES DE CHIMBORAZO', True ),
    ('9989', 'COOP AHO Y CREDITO MANUEL GODOY',         True ),
    ('9991', 'COOP AHO Y CREDITO SAN JOSE',             True ),
    ('9985', 'COOP AHO Y CREDITO SANTA ROSA',           True ),
    ('312',  'COOP AHORRO Y CREDI MUJERES UNIDAS TANTANAKUSHKA W', True ),
    ('311',  'COOP AHORRO Y CREDITO SAN GABRIEL LTDA',  True ),
    ('324',  'COOP AHORRO Y CREDITO SAN ISIDRO LTDA',   True ),
    ('404',  'COOP DE A Y C FUTURO LAMANENSE',          True ),
    ('342',  'COOP DE A Y C SAN JUAN DE COTOGCHOA',     True ),
    ('431',  'COOP DE A Y C SANTA ANA DE NAYON',        True ),
    ('308',  'COOP DE A Y CR CORPORACION CENTRO LTDA',  True ),
    ('9972', 'COOP DE AH Y CR CONSTRUCCION COMERCIO Y PRODUCCION', True ),
    ('598',  'COOP DE AH Y CR CREDI YA LTDA.',          True ),
    ('161',  'COOP DE AH Y CR DE SERV PUBLIC MINISTERIO EDUC Y C', True ),
    ('538',  'COOP DE AH Y CR ECUACREDITOS LTDA',       True ),
    ('354',  'COOP DE AH Y CR ERCO LTDA.',              True ),
    ('591',  'COOP DE AH Y CR GANANSOL LTDA',           True ),
    ('593',  'COOP DE AH Y CR NACIONAL LLANO GRANDE LTDA.', True ),
    ('372',  'COOP DE AH Y CR NUEVA ESPERANZA',         True ),
    ('594',  'COOP DE AH Y CR OBRAS PUBLICAS FISCALES DE LOJA Y', True ),
    ('597',  'COOP DE AH Y CR SAN MIGUEL LTDA.',        True ),
    ('221',  'COOP DE AHO Y CRED SAN MIGUEL DE LOS BANCOS', True ),
    ('299',  'COOP DE AHORRO Y CREDITO LA MERCED LTDA', True ),
    ('395',  'COOP DE AHORRO Y CREDITO PROVIDA',        True ),
    ('355',  'COOP DE AHORRO Y CREDITO SANTA ISABEL LTDA', True ),
    ('9995', 'COOP. 29 DE OCTUBRE',                     True ),
    ('135',  'COOP. A Y C DE LA PEQ. EMP. CACPE ZAMORA LTDA.', True ),
    ('537',  'COOP. AH Y CR SAN ANTONIO LTDA. - IMBABURA (MIES)', True ),
    ('534',  'COOP. AH Y CR SUMAK KAWSAY',              True ),
    ('535',  'COOP. AH Y CR VISIONFUND ECUADOR S. A.',  True ),
    ('139',  'COOP. AHO Y CRED ALIANZA MINAS LTDA.',    True ),
    ('9975', 'COOP. AHO Y CREDITO 23 DE JULIO',         True ),
    ('9986', 'COOP. AHO Y CREDITO EL SAGRARIO',         True ),
    ('9993', 'COOP. AHO Y CREDITO JARDIN AZUAYO',       True ),
    ('9992', 'COOP. AHO Y CREDITO SAN FRANCISCO',       True ),
    ('9976', 'COOP. AHO Y CREDITO SANTA ANA',           True ),
    ('100',  'COOP. AHORRO Y CREDITO 15 DE ABRIL LTDA', True ),
    ('129',  'COOP. AHORRO Y CREDITO AGRARIA MUSHUK KAWSAY LTDA.', True ),
    ('102',  'COOP. AHORRO Y CREDITO CARIAMANGA LTDA.', True ),
    ('9965', 'COOP. AHORRO Y CREDITO COOPROGRESO',      True ),
    ('131',  'COOP. AHORRO Y CREDITO DE LA PEQUENA EMPRESA GUALA', True ),
    ('134',  'COOP. AHORRO Y CREDITO FUNDESARROLLO',    True ),
    ('125',  'COOP. AHORRO Y CREDITO JUAN DE SALINAS LTDA.', True ),
    ('124',  'COOP. AHORRO Y CREDITO MANANTIAL DE ORO LTDA.', True ),
    ('132',  'COOP. AHORRO Y CREDITO MI TIERRA',        True ),
    ('126',  'COOP. AHORRO Y CREDITO NUEVA JERUSALEN',  True ),
    ('103',  'COOP. AHORRO Y CREDITO PUELLARO LTDA',    True ),
    ('327',  'COOP. AHORRO Y CREDITO SEMILLA DEL PROGRESO LTDA.', True ),
    ('130',  'COOP. AHORRO Y CREDITO TENA LTDA.',       True ),
    ('9977', 'COOP. ALIANZA DEL VALLE LTDA.',           True ),
    ('9998', 'COOP. ANDALUCIA',                         True ),
    ('9983', 'COOP. ATUNTAQUI',                         True ),
    ('9982', 'COOP. CACPECO',                           True ),
    ('9971', 'COOP. CALCETA LTDA.',                     True ),
    ('9981', 'COOP. CHONE LTDA.',                       True ),
    ('9980', 'COOP. COMERCIO LTDA PORTOVIEJO',          True ),
    ('9994', 'COOP. COTOCOLLAO',                        True ),
    ('302',  'COOP. DE A Y C GUAMOTE LTDA',             True ),
    ('293',  'COOP. DE A Y C. LUZ DEL VALLE',           True ),
    ('315',  'COOP. DE A. Y C. 13 DE ABRIL LTDA',       True ),
    ('105',  'COOP. DE A. Y C. 16 DE JUNIO',            True ),
    ('107',  'COOP. DE A. Y C. 23 DE MAYO LTDA.',       True ),
    ('331',  'COOP. DE A. Y C. ABDON CALDERON LTDA.',   True ),
    ('306',  'COOP. DE A. Y C. CAMARA DE COMERCIO SANTO DOMINGO', True ),
    ('320',  'COOP. DE A. Y C. CHIBULEO LTDA.',         True ),
    ('318',  'COOP. DE A. Y C. COOPAC AUSTRO LTDA -MIESS', True ),
    ('303',  'COOP. DE A. Y C. CREDISOCIO',             True ),
    ('359',  'COOP. DE A. Y C. LUCHA CAMPESINA LTDA.',  True ),
    ('108',  'COOP. DE A. Y C. MAQUITA CUSHUNCHIC LTDA.', True ),
    ('440',  'COOP. DE AH Y CR 1 DE JULIO',             True ),
    ('509',  'COOP. DE AH Y CR 16 DE JULIO LTDA',       True ),
    ('576',  'COOP. DE AH Y CR 17 DE MARZO LTDA',       True ),
    ('564',  'COOP. DE AH Y CR ACCION IMBABURAPAK LTDA.', True ),
    ('568',  'COOP. DE AH Y CR ACCION TUNGURAHUA LTDA', True ),
    ('489',  'COOP. DE AH Y CR ALFONSO JARAMILLO C.C.C.', True ),
    ('577',  'COOP. DE AH Y CR BASE DE TAURA',          True ),
    ('487',  'COOP. DE AH Y CR CACEC LTDA. COTOPAXI',   True ),
    ('486',  'COOP. DE AH Y CR CACPE CELICA',           True ),
    ('602',  'COOP. DE AH Y CR CAMARA DE COMERCIO DEL CANTON BOL', True ),
    ('526',  'COOP. DE AH Y CR CAMARA DE COMERCIO JOYA DE LOS SA', True ),
    ('603',  'COOP. DE AH Y CR CASAG LTDA',             True ),
    ('606',  'COOP. DE AH Y CR CREDISUR LTDA.',         True ),
    ('572',  'COOP. DE AH Y CR DON BOSCO',              True ),
    ('596',  'COOP. DE AH Y CR EDUC. DEL TUNGURAHUA LTDA.', True ),
    ('522',  'COOP. DE AH Y CR EDUCADORES DE LOJA',     True ),
    ('513',  'COOP. DE AH Y CR EDUCADORES DE ZAMORA CHINCHIPE', True ),
    ('512',  'COOP. DE AH Y CR EDUCADORES TULCAN LTDA', True ),
    ('582',  'COOP. DE AH Y CR EL MOLINO LTDA.',        True ),
    ('533',  'COOP. DE AH Y CR ESPERANZA DEL FUTURO LTDA', True ),
    ('470',  'COOP. DE AH Y CR FOCLA',                  True ),
    ('575',  'COOP. DE AH Y CR FONDO PARA EL DESARROLLO Y LA VID', True ),
    ('373',  'COOP. DE AH Y CR FORTUNA - MIES',         True ),
    ('595',  'COOP. DE AH Y CR FUTURO Y PROGRESO DE GALAPAGOS LT', True ),
    ('524',  'COOP. DE AH Y CR GRAMEEN AMAZONAS',       True ),
    ('467',  'COOP. DE AH Y CR INDIGENA SAC LTDA',      True ),
    ('567',  'COOP. DE AH Y CR KULLKI WASI LTDA.',      True ),
    ('552',  'COOP. DE AH Y CR LA FLORESTA LTDA.',      True ),
    ('291',  'COOP. DE AH Y CR LA INMACULADA DE SAN PLACIDO LTDA', True ),
    ('517',  'COOP. DE AH Y CR LIMITADA MIFEX',         True ),
    ('605',  'COOP. DE AH Y CR LOS RIOS',               True ),
    ('488',  'COOP. DE AH Y CR MAGISTERIO MANABITA LIMITADA', True ),
    ('510',  'COOP. DE AH Y CR METROPOLIS LTDA.',       True ),
    ('581',  'COOP. DE AH Y CR MUSHUK - YUYAY (CANAR)', True ),
    ('585',  'COOP. DE AH Y CR OCCIDENTAL',             True ),
    ('155',  'COOP. DE AH Y CR ONCE DE JUNIO',          True ),
    ('529',  'COOP. DE AH Y CR PADRE VICENTE PONCE RUBIO', True ),
    ('498',  'COOP. DE AH Y CR PARA LA VIVIENDA ORDEN Y SEGURIDA', True ),
    ('525',  'COOP. DE AH Y CR PUERTO FRANCISCO DE ORELLANA', True ),
    ('583',  'COOP. DE AH Y CR PUSHAK RUNA HOMBRE LIDER', True ),
    ('550',  'COOP. DE AH Y CR SAN JOSE S.J.',          True ),
    ('479',  'COOP. DE AH Y CR SANTA LUCIA LTDA',       True ),
    ('508',  'COOP. DE AH Y CR SANTA MARIA DE LA MANGA DEL CURA', True ),
    ('604',  'COOP. DE AH Y CR SANTA ROSA DE PATUTAN LTDA.', True ),
    ('520',  'COOP. DE AH Y CR SERVIDORES MUNICIPALES DE CUENCA', True ),
    ('555',  'COOP. DE AH Y CR SIERRA CENTRO',          True ),
    ('554',  'COOP. DE AH Y CR SOL DE LOS ANDES LTDA.', True ),
    ('457',  'COOP. DE AH Y CR TEXTIL 14 DE MARZO',     True ),
    ('587',  'COOP. DE AH Y CR UNIBLOCK Y SERVICIOS LTDA.', True ),
    ('573',  'COOP. DE AH Y CR VENCEDORES DE TUNGURAHUA', True ),
    ('506',  'COOP. DE AH Y CR VIRGEN DEL CISNE',       True ),
    ('586',  'COOP. DE AH Y CR. SIMON BOLIVAR',         True ),
    ('511',  'COOP. DE AH. Y CR. SAN MARTIN DE TISALEO LTDA.', True ),
    ('323',  'COOP. DE AHORRO Y CREDITO 4 DE OCTUBRE LTDA.', True ),
    ('133',  'COOP. DE AHORRO Y CREDITO DE LA PEQ. EMP. CACPE YA', True ),
    ('328',  'COOP. DE AHORRO Y CREDITO HUAICANA LTDA', True ),
    ('301',  'COOP. DE AHORRO Y CREDITO LOS ANDES LATINOS LTDA.', True ),
    ('263',  'COOP. DE AHORRO Y CREDITO MUSHUC RUNA LTDA.', True ),
    ('275',  'COOP. DE AHORRO Y CREDITO NUEVA HUANCAVILCA LTDA.', True ),
    ('300',  'COOP. DE AHORRO Y CREDITO PEDRO MONCAYO LTDA.', True ),
    ('316',  'COOP. DE AHORRO Y CREDITO PILAHUIN TIO LTDA.', True ),
    ('109',  'COOP. DE AHORRO Y CREDITO SAN FRANCISCO DE ASIS LT', True ),
    ('426',  'COOP. DE AHORRO Y CREDITO SAN MIGUEL DE PALLATANGA', True ),
    ('187',  'COOP. DE AHORRO Y CREDITO SR. DE GIRON',  True ),
    ('9984', 'COOP. GUARANDA',                          True ),
    ('9974', 'COOP. JUVENTUD ECUATORIANA PROGRESISTA LTDA.', True ),
    ('9988', 'COOP. LA DOLOROSA',                       True ),
    ('9987', 'COOP. OSCUS',                             True ),
    ('9970', 'COOP. PABLO MUNOZ VEGA',                  True ),
    ('9997', 'COOP. PEQ. EMPRESA DE PASTAZA',           True ),
    ('9999', 'COOP. PREVISION AHORRO Y DESARROLLO',     True ),
    ('9979', 'COOP. RIOBAMBA',                          True ),
    ('9969', 'COOP. TULCAN',                            True ),
    ('446',  'COOP.DE AHORRO Y CREDITO MICROEMPRESARIAL SUCRE', True ),
    ('205',  'COOPE AHO Y CRED PADRE JULIAN LORENTE LTDA', True ),
    ('233',  'COOPE.CAMARA DE COMERCIO DE AMBATO',      True ),
    ('143',  'COOPERATIVA 9 DE OCTUBRE LTDA',           True ),
    ('144',  'COOPERATIVA CACPE BIBLIAN LTDA',          True ),
    ('579',  'COOPERATIVA DE AH Y CR CANAR LTDA.',      True ),
    ('405',  'COOPERATIVA DE AHORO Y CREDITO VISION DE LOS ANDES', True ),
    ('313',  'COOPERATIVA DE AHORRO Y CREDITO ARTESANOS LTDA', True ),
    ('319',  'COOPERATIVA DE AHORRO Y CREDITO CREA LTDA -MIES', True ),
    ('296',  'COOPERATIVA DE AHORRO Y CREDITO FERNANDO DAQUILEMA', True ),
    ('295',  'COOPERATIVA DE AHORRO Y CREDITO LA BENEFICA LTDA', True ),
    ('397',  'COOPERATIVA DE AHORRO Y CREDITO LAS LAGUNAS-MIESS', True ),
    ('353',  'COOPERATIVA DE AHORRO Y CREDITO MINGA LTDA', True ),
    ('341',  'COOPERATIVA DE AHORRO Y CREDITO MULTIEMPRESARIAL L', True ),
    ('338',  'COOPERATIVA DE AHORRO Y CREDITO PUCARA LTDA', True ),
    ('314',  'COOPERATIVA DE AHORRO Y CREDITO SANTA ANITA LTDA', True ),
    ('9963', 'CORPORACION FINANCIERA',                  True ),
    ('185',  'Coop Ah y Cr de la Pequena Empresa de Loja CACPE L', True ),
    ('204',  'Coop Ah y Credito Ambato Ltda',           True ),
    ('43',   'DEL LITORAL',                             True ),
    ('27',   'DELBANK',                                 True ),
    ('9967', 'DINERS CLUB',                             True ),
    ('1015', 'DINERS/VISA INTERDIN/DISCOVER - Transferencias EnL', True ),
    ('140',  'ECUATORIANO DE LA VIVIENDA',              True ),
    ('9964', 'FINANCIERA FINANCOOP',                    True ),
    ('17',   'GUAYAQUIL',                               True ),
    ('32',   'INTERNACIONAL',                           True ),
    ('29',   'LOJA',                                    True ),
    ('25',   'MACHALA',                                 True ),
    ('87',   'MUTUALISTA AMBATO',                       True ),
    ('88',   'MUTUALISTA AZUAY',                        True ),
    ('85',   'MUTUALISTA IMBABURA',                     True ),
    ('86',   'MUTUALISTA PICHINCHA',                    True ),
    ('30',   'PACIFICO',                                True ),
    ('10',   'PICHINCHA',                               True ),
    ('36',   'PRODUBANCO',                              True ),
    ('42',   'RUMINAHUI',                               True ),
    ('59',   'SOLIDARIO',                               True ),
    ('63',   'BANCO D MIRO SA',                         False),
    ('123',  'BANCO PARA LA ASISTENCIA COMUNITARIA FINCA S.A.', False),
    ('601',  'CCU EP CNT EP CARCHI',                    False),
    ('9978', 'COOP AHO Y CREDITO DESARROLLO PUEBLOS',   False),
    ('309',  'COOP DE A. Y C. ANTORCHA LTDA',           False),
    ('435',  'COOP DE AH Y CR AGRICOLA JUNIN LTDA',     False),
    ('578',  'COOP DE AH Y CR HERMES GAIBOR VERDESOTO', False),
    ('547',  'COOP. AH Y CR SAN MIGUEL DE SIGCHOS',     False),
    ('9990', 'COOP. AHO Y CREDITO NACIONAL',            False),
    ('3456', 'COOP. AHORRO Y CREDITO ALIANZA MINAS LTDA.', False),
    ('106',  'COOP. DE A. Y C. 20 DE FEBRERO LTDA.',    False),
    ('461',  'COOP. DE AH Y CR CAMARA DE COMERCIO RIOBAMBA', False),
    ('514',  'COOP. DE AH Y CR COOPARTAMOS LTDA',       False),
    ('499',  'COOP. DE AH Y CR ECUAFUTURO LTDA.',       False),
    ('561',  'COOP. DE AH Y CR INDIGENAS GALAPAGOS LTDA', False),
    ('560',  'COOP. DE AH Y CR SINCHI RUNA LTDA',       False),
    ('553',  'COOP. DE AH Y CR UNIOTAVALO LTDA.',       False),
    ('322',  'COOP.DE AHORRO Y CREDITO HUAYCO PUNGO LTDA.', False),
    ('546',  'COOPERATIVA CREDIMAS',                    False),
    ('317',  'COOPERATIVA DE AHORRO Y CREDITO PILAHUIN', False),
    ('9966', 'DELBANK S.A.',                            False),
    ('137',  'INST POLICIA SEGURO SOCIAL NACIONAL',     False),
]

# Los que se pueden elegir al pagar: activos y con SPI habilitado
BANCOS_ACTIVOS = [(c, n) for c, n, ok in BANCOS if ok]
BANCOS_POR_CODIGO = {c: n for c, n, _ in BANCOS}


def nombre_banco(codigo):
    """El nombre para mostrar. Devuelve el codigo si no esta en el catalogo:
    mejor ver un numero raro que una celda vacia."""
    import re
    c = re.sub(r'[^0-9]', '', str(codigo or ''))
    return BANCOS_POR_CODIGO.get(c, c or '')


def codigo_txt(codigo):
    """El TXT del banco pide el codigo en CUATRO digitos: 36 va como 0036.
    Diners es 9967 y ya trae cuatro."""
    import re
    c = re.sub(r'[^0-9]', '', str(codigo or ''))
    return c.zfill(4) if c else ''
